global:
  resolve_timeout: 5m

route:
  group_by: [ 'alertname', 'severity' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  routes:
  - match:
      severity: critical
    receiver: slack-notifications
  - match:
      severity: warning
    receiver: email-notifications
  receiver: email-notifications

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'hamzazaafrane@gmail.com'
    from: 'zaafranetest@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'hamzazaafrane@gmail.com'
    auth_identity: 'hamzazaafrane@gmail.com'
    auth_password: 'owsnuglwrqthzyqsc'
    send_resolved: true

- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/T07f4ZQDK602/B085BhdfhAG8198/cBnNWeqhhhdfh1frxsXU20HQUEm'
    channel: '#alerts'
    send_resolved: true
    title: '{{ .CommonLabels.alertname }} - {{ .CommonLabels.severity }}'
    text: |
      *Alert*: {{ .CommonLabels.alertname }}
      *Severity*: {{ .CommonLabels.severity }}
      *Details*: {{ .CommonAnnotations.description }}
      {{ range .Alerts }}
      - *Instance*: {{ .Labels.instance }}
      - *Job*: {{ .Labels.job }}
      - *Triggered At*: {{ .StartsAt }}
      {{ end }}
