auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory # Use in-memory KV store for a single instance
      replication_factor: 1 # Single instance does not need replication
    final_sleep: 0s

schema_config:
  configs:
  - from: 2024-01-01
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 168h # Retain logs for 7 days
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  reject_old_samples: true
  allow_structured_metadata: false
  reject_old_samples_max_age: 336h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h # Retain logs for 7 days

compactor:
  working_directory: /loki/compactor
