auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory # Use in-memory KV store for a single instance
      replication_factor: 1 # Single instance does not need replication
    final_sleep: 0s

schema_config:
  configs:
  - from: 2024-01-01
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 720h # Retain logs for 30 days
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h # Retain logs for 30 days

compactor:
  working_directory: /loki/compactor

# auth_enabled: false

# server:
#   http_listen_port: 3100

# ingester:
#   lifecycler:
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#   wal:
#     enabled: true
#     dir: /wal

# schema_config:
#   configs:
#   - from: 2020-10-24
#     store: boltdb-shipper
#     object_store: filesystem
#     schema: v11
#     index:
#       prefix: index_
#       period: 24h

# storage_config:
#   boltdb_shipper:
#     active_index_directory: /loki/index
#     cache_location: /loki/cache
#     shared_store: filesystem
#   filesystem:
#     directory: /loki/chunks

# limits_config:
#   enforce_metric_name: false
#   reject_old_samples: true
#   reject_old_samples_max_age: 168h
#   ingestion_rate_mb: 4
#   ingestion_burst_size_mb: 6
#   max_query_parallelism: 2
#   max_query_length: 6h
#   query_timeout: 2m

# chunk_store_config:
#   max_look_back_period: 0s

# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 168h

# compactor:
#   working_directory: /loki/compactor
